/**
 * Centralized error codes — SINGLE SOURCE OF TRUTH.
 * Never define error codes inline in apps.
 */
export const ErrorCode = {
  // Auth (401)
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",

  // Forbidden (403)
  FORBIDDEN: "FORBIDDEN",
  INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",

  // Not Found (404)
  NOT_FOUND: "NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  WORKSPACE_NOT_FOUND: "WORKSPACE_NOT_FOUND",

  // Conflict (409)
  CONFLICT: "CONFLICT",
  WORKSPACE_SLUG_EXISTS: "WORKSPACE_SLUG_EXISTS",
  USER_ALREADY_MEMBER: "USER_ALREADY_MEMBER",

  // Validation (400)
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_INPUT: "INVALID_INPUT",

  // Business Logic (422)
  BUSINESS_LOGIC_ERROR: "BUSINESS_LOGIC_ERROR",
  PLAN_LIMIT_REACHED: "PLAN_LIMIT_REACHED",
  WORKSPACE_REQUIRED: "WORKSPACE_REQUIRED",
  NO_WORKSPACE_MEMBERSHIP: "NO_WORKSPACE_MEMBERSHIP",

  // Rate Limit (429)
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

  // Server Error (500)
  INTERNAL_ERROR: "INTERNAL_ERROR",
  ENCRYPTION_FAILED: "ENCRYPTION_FAILED",
  DATABASE_ERROR: "DATABASE_ERROR",
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
