import React from "react";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function PolicyPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-16 sm:py-24">
      <Link
        href="/"
        className="inline-flex items-center text-sm text-muted-foreground hover:text-foreground mb-8 transition-colors"
      >
        <ArrowLeft className="mr-2 size-4" />
        Back to home
      </Link>

      <div className="space-y-6">
        <div>
          <h1 className="text-2xl font-serif tracking-tight mb-2">
            Privacy Policy
          </h1>
          <p className="text-muted-foreground text-sm">
            Last updated: {new Date().toLocaleDateString()}
          </p>
        </div>

        <div className="h-px w-full bg-border my-8" />

        <div className="space-y-4">
          <p className="text-muted-foreground leading-6 text-sm">
            We collect several different types of information for various
            purposes to provide and improve our Service to you.
          </p>
        </div>

        <section className="space-y-4">
          <h2 className="text-lg tracking-tight mt-10">
            Definitions
          </h2>

          <h3 className="text-base mt-6">Service</h3>
          <p className="text-muted-foreground leading-6 text-sm">
            Service is the Oewang application operated by Oewang
          </p>

          <h3 className="text-base mt-6">Personal Data</h3>
          <p className="text-muted-foreground leading-6 text-sm">
            Personal Data means data about a living individual who can be
            identified from those data (or from those and other information
            either in our possession or likely to come into our possession).
          </p>

          <h3 className="text-base mt-6">Usage Data</h3>
          <p className="text-muted-foreground leading-6 text-sm">
            Usage Data is data collected automatically either generated by the
            use of the Service or from the Service infrastructure itself (for
            example, the duration of a page visit).
          </p>

          <h3 className="text-base mt-6">Cookies</h3>
          <p className="text-muted-foreground leading-6 text-sm">
            Cookies are small files stored on your device (computer or mobile
            device).
          </p>

          <h3 className="text-base mt-6">Data Controller</h3>
          <p className="text-muted-foreground leading-6 text-sm">
            Data Controller means the natural or legal person who (either alone
            or jointly or in common with other persons) determines the purposes
            for which and the manner in which any personal information are, or
            are to be, processed.
          </p>
          <p className="text-muted-foreground leading-6 text-sm">
            For the purpose of this Privacy Policy, we are a Data Controller of
            your Personal Data.
          </p>

          <h3 className="text-base mt-6">
            Data Processors (or Service Providers)
          </h3>
          <p className="text-muted-foreground leading-6 text-sm">
            Data Processor (or Service Provider) means any natural or legal
            person who processes the data on behalf of the Data Controller.
          </p>
          <p className="text-muted-foreground leading-6 text-sm">
            We may use the services of various Service Providers in order to
            process your data more effectively.
          </p>

          <h3 className="text-base mt-6">Data Subject (or User)</h3>
          <p className="text-muted-foreground leading-6 text-sm">
            Data Subject is any living individual who is using our Service and
            is the subject of Personal Data.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg tracking-tight mt-10">
            Use of Data
          </h2>
          <p className="text-muted-foreground leading-6 text-sm">
            Oewang uses the collected data for various purposes:
          </p>
          <ul className="list-disc pl-6 space-y-2 text-muted-foreground leading-6 text-sm">
            <li>To provide and maintain our Service</li>
            <li>To notify you about changes to our Service</li>
            <li>
              To allow you to participate in interactive features of our Service
              when you choose to do so
            </li>
            <li>To provide customer support</li>
            <li>
              To gather analysis or valuable information so that we can improve
              our Service
            </li>
            <li>To monitor the usage of our Service</li>
            <li>To detect, prevent and address technical issues</li>
            <li>
              To provide you with news, special offers and general information
              about other goods, services and events which we offer that are
              similar to those that you have already purchased or enquired about
              unless you have opted not to receive such information
            </li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg tracking-tight mt-10">
            Use of Google User Data
          </h2>
          <p className="text-muted-foreground leading-6 text-sm">
            Oewang's use of information received from Google APIs will adhere to
            the Google API Services User Data Policy, including the Limited Use
            requirements.
          </p>
          <p className="text-muted-foreground leading-6 text-sm">
            We do not use any data obtained from Google Workspace APIs —
            including Gmail data — to develop, improve, or train generalized
            artificial intelligence (AI) or machine learning (ML) models.
          </p>
          <p className="text-muted-foreground leading-6 text-sm">
            User data accessed via Gmail scopes is used strictly for the purpose
            of reading and extracting relevant information from emails (such as
            invoices and receipts) to help users automate and manage their
            business finances. This data is never shared, sold, or used for
            advertising purposes.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg tracking-tight mt-10">
            Legal Basis for Processing Personal Data under the GDPR
          </h2>
          <p className="text-muted-foreground leading-6 text-sm">
            If you are from the European Economic Area (EEA), Oewang legal basis
            for collecting and using the personal information described in this
            Privacy Policy depends on the Personal Data we collect and the
            specific context in which we collect it.
          </p>
          <p className="text-muted-foreground leading-6 text-sm">
            Oewang may process your Personal Data because:
          </p>
          <ul className="list-disc pl-6 space-y-2 text-muted-foreground leading-6 text-sm">
            <li>We need to perform a contract with you</li>
            <li>You have given us permission to do so</li>
            <li>
              The processing is in our legitimate interests and it is not
              overridden by your rights
            </li>
            <li>For payment processing purposes</li>
            <li>To comply with the law</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg tracking-tight mt-10">
            Retention of Data
          </h2>
          <p className="text-muted-foreground leading-6 text-sm">
            Oewang will retain your Personal Data only for as long as is
            necessary for the purposes set out in this Privacy Policy. We will
            retain and use your Personal Data to the extent necessary to comply
            with our legal obligations (for example, if we are required to
            retain your data to comply with applicable laws), resolve disputes
            and enforce our legal agreements and policies.
          </p>
          <p className="text-muted-foreground leading-6 text-sm">
            Oewang will also retain Usage Data for internal analysis purposes.
            Usage Data is generally retained for a shorter period of time,
            except when this data is used to strengthen the security or to
            improve the functionality of our Service, or we are legally
            obligated to retain this data for longer periods.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg tracking-tight mt-10">
            Transfer of Data
          </h2>
          <p className="text-muted-foreground leading-6 text-sm">
            Your information, including Personal Data, may be transferred to -
            and maintained on - computers located outside of your state,
            province, country or other governmental jurisdiction where the data
            protection laws may differ from those of your jurisdiction.
          </p>
          <p className="text-muted-foreground leading-6 text-sm">
            If you are located outside your hosting provider's country and
            choose to provide information to us, please note that we transfer
            the data, including Personal Data, to that facility and process it
            there.
          </p>
          <p className="text-muted-foreground leading-6 text-sm">
            Your consent to this Privacy Policy followed by your submission of
            such information represents your agreement to that transfer.
          </p>
          <p className="text-muted-foreground leading-6 text-sm">
            Oewang will take all the steps reasonably necessary to ensure that
            your data is treated securely and in accordance with this Privacy
            Policy and no transfer of your Personal Data will take place to an
            organisation or a country unless there are adequate controls in
            place including the security of your data and other personal
            information.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg tracking-tight mt-10">
            Disclosure of Data
          </h2>

          <h3 className="text-base mt-6">Business Transaction</h3>
          <p className="text-muted-foreground leading-6 text-sm">
            If Oewang is involved in a merger, acquisition or asset sale, your
            Personal Data may be transferred. We will provide notice before your
            Personal Data is transferred and becomes subject to a different
            Privacy Policy.
          </p>

          <h3 className="text-base mt-6">
            Disclosure for Law Enforcement
          </h3>
          <p className="text-muted-foreground leading-6 text-sm">
            Under certain circumstances, Oewang may be required to disclose your
            Personal Data if required to do so by law or in response to valid
            requests by public authorities (e.g. a court or a government
            agency).
          </p>

          <h3 className="text-base mt-6">Legal Requirements</h3>
          <p className="text-muted-foreground leading-6 text-sm">
            Oewang may disclose your Personal Data in the good faith belief that
            such action is necessary to:
          </p>
          <ul className="list-disc pl-6 space-y-2 text-muted-foreground leading-6 text-sm">
            <li>To comply with a legal obligation</li>
            <li>To protect and defend the rights or property of Oewang</li>
            <li>
              To prevent or investigate possible wrongdoing in connection with
              the Service
            </li>
            <li>
              To protect the personal safety of users of the Service or the
              public
            </li>
            <li>To protect against legal liability</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg tracking-tight mt-10">
            Security of Data
          </h2>
          <p className="text-muted-foreground leading-6 text-sm">
            The security of your data is important to us but remember that no
            method of transmission over the Internet or method of electronic
            storage is 100% secure. While we strive to use commercially
            acceptable means to protect your Personal Data, we cannot guarantee
            its absolute security.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg tracking-tight mt-10">
            Your Data Protection Rights under the GDPR
          </h2>
          <p className="text-muted-foreground leading-6 text-sm">
            If you are a resident of the European Economic Area (EEA), you have
            certain data protection rights. Oewang aims to take reasonable steps
            to allow you to correct, amend, delete or limit the use of your
            Personal Data.
          </p>
          <p className="text-muted-foreground leading-6 text-sm">
            If you wish to be informed about what Personal Data we hold about
            you and if you want it to be removed from our systems, please
            contact us.
          </p>
          <p className="text-muted-foreground leading-6 text-sm">
            In certain circumstances, you have the following data protection
            rights:
          </p>
          <ul className="list-disc pl-6 space-y-2 text-muted-foreground leading-6 text-sm">
            <li>
              The right to access, update or delete the information we have on
              you. Whenever made possible, you can access, update or request
              deletion of your Personal Data directly within your account
              settings section. If you are unable to perform these actions
              yourself, please contact us to assist you.
            </li>
            <li>
              The right of rectification. You have the right to have your
              information rectified if that information is inaccurate or
              incomplete.
            </li>
            <li>
              The right to object. You have the right to object to our
              processing of your Personal Data.
            </li>
            <li>
              The right of restriction. You have the right to request that we
              restrict the processing of your personal information.
            </li>
            <li>
              The right to data portability. You have the right to be provided
              with a copy of the information we have on you in a structured,
              machine-readable and commonly used format.
            </li>
            <li>
              The right to withdraw consent. You also have the right to withdraw
              your consent at any time where Oewang relied on your consent to
              process your personal information.
            </li>
          </ul>
          <p className="text-muted-foreground leading-6 text-sm">
            Please note that we may ask you to verify your identity before
            responding to such requests.
          </p>
          <p className="text-muted-foreground leading-6 text-sm">
            You have the right to complain to a Data Protection Authority about
            our collection and use of your Personal Data. For more information,
            please contact your local data protection authority in the European
            Economic Area (EEA).
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg tracking-tight mt-10">
            Children's Privacy
          </h2>
          <p className="text-muted-foreground leading-6 text-sm">
            Our Service does not address anyone under the age of 18
            ("Children").
          </p>
          <p className="text-muted-foreground leading-6 text-sm">
            We do not knowingly collect personally identifiable information from
            anyone under the age of 18. If you are a parent or guardian and you
            are aware that your Child has provided us with Personal Data, please
            contact us. If we become aware that we have collected Personal Data
            from children without verification of parental consent, we take
            steps to remove that information from our servers.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg tracking-tight mt-10">
            Changes to This Privacy Policy
          </h2>
          <p className="text-muted-foreground leading-6 text-sm">
            We may update our Privacy Policy from time to time. We will notify
            you of any changes by posting the new Privacy Policy on this page.
          </p>
          <p className="text-muted-foreground leading-6 text-sm">
            We will let you know via email and/or a prominent notice on our
            Service, prior to the change becoming effective and update the
            "effective date" at the top of this Privacy Policy.
          </p>
          <p className="text-muted-foreground leading-6 text-sm">
            You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are
            posted on this page.
          </p>
        </section>

        <section className="space-y-4 mb-20">
          <h2 className="text-lg tracking-tight mt-10">
            Contact Us
          </h2>
          <p className="text-muted-foreground leading-6 text-sm">
            If you have any questions about this Privacy Policy, please contact
            us through our administrative support channels.
          </p>
        </section>
      </div>
    </div>
  );
}
