export type ShortcutDateRangePreset = "last7Days" | "lastMonthToNow" | "thisMonth" | "yearToDate";

export interface ChatShortcutTemplate {
  command: "/show" | "/find" | "/analyze";
  titleKey: string;
  titleDefault: string;
  toolName: string;
  toolParams: Record<string, unknown>;
  keywords: string[];
  dateRangePreset?: ShortcutDateRangePreset;
}

export const CHAT_SHORTCUT_TEMPLATES: ChatShortcutTemplate[] = [
  {
    command: "/show",
    titleKey: "chat.shortcuts.show_latest_transactions",
    titleDefault: "Show latest transactions",
    toolName: "getTransactions",
    toolParams: { pageSize: 10, sort: ["date", "desc"] },
    keywords: ["show", "latest", "transactions", "recent"],
  },
  {
    command: "/show",
    titleKey: "chat.shortcuts.show_monthly_spending_hotspots",
    titleDefault: "Show monthly spending hotspots",
    toolName: "getBurnRate",
    toolParams: { showCanvas: true },
    keywords: ["show", "burn", "cash", "spending", "analysis"],
  },
  {
    command: "/show",
    titleKey: "chat.shortcuts.show_spending_most_this_month",
    titleDefault: "Show where we spend the most this month",
    toolName: "getSpending",
    toolParams: { showCanvas: true },
    dateRangePreset: "thisMonth",
    keywords: ["show", "spending", "most", "this month", "where", "expense"],
  },
  {
    command: "/analyze",
    titleKey: "chat.shortcuts.analyze_weekly_trends",
    titleDefault: "Analyze weekly trends and insights",
    toolName: "getCashFlow",
    toolParams: { showCanvas: true },
    dateRangePreset: "last7Days",
    keywords: ["analyze", "weekly", "trends", "insights"],
  },
  {
    command: "/show",
    titleKey: "chat.shortcuts.show_revenue_performance",
    titleDefault: "Show revenue performance",
    toolName: "getRevenueSummary",
    toolParams: { showCanvas: true },
    dateRangePreset: "yearToDate",
    keywords: ["show", "revenue", "performance", "income"],
  },
  {
    command: "/show",
    titleKey: "chat.shortcuts.show_expense_breakdown_category",
    titleDefault: "Show expense breakdown by category",
    toolName: "getSpending",
    toolParams: { showCanvas: true },
    keywords: ["show", "expense", "breakdown", "category"],
  },
  {
    command: "/show",
    titleKey: "chat.shortcuts.show_cash_runway",
    titleDefault: "Show cash runway",
    toolName: "getRunway",
    toolParams: { showCanvas: true },
    keywords: ["show", "runway", "cash", "left"],
  },
  {
    command: "/analyze",
    titleKey: "chat.shortcuts.analyze_cashflow_stress_test",
    titleDefault: "Analyze cash flow stress test",
    toolName: "getCashFlowStressTest",
    toolParams: { showCanvas: true },
    keywords: ["analyze", "stress", "test", "scenario", "resilience", "financial"],
  },
  {
    command: "/find",
    titleKey: "chat.shortcuts.find_uncategorized_transactions",
    titleDefault: "Find uncategorized transactions from last month",
    toolName: "getTransactions",
    toolParams: { statuses: ["pending"] },
    dateRangePreset: "lastMonthToNow",
    keywords: ["find", "uncategorized", "transactions", "last month", "clean", "untagged"],
  },
  {
    command: "/find",
    titleKey: "chat.shortcuts.find_recurring_payments",
    titleDefault: "Find recurring payments",
    toolName: "getTransactions",
    toolParams: { recurring: true },
    keywords: ["find", "recurring", "payments", "subscriptions"],
  },
  {
    command: "/analyze",
    titleKey: "chat.shortcuts.analyze_spending_patterns",
    titleDefault: "Analyze spending patterns",
    toolName: "getSpending",
    toolParams: { showCanvas: true },
    keywords: ["analyze", "spending", "patterns"],
  },
  {
    command: "/show",
    titleKey: "chat.shortcuts.show_profit_loss",
    titleDefault: "Show profit and loss statement",
    toolName: "getProfitAnalysis",
    toolParams: { showCanvas: true },
    keywords: ["show", "profit", "loss", "statement", "p&l"],
  },
  {
    command: "/analyze",
    titleKey: "chat.shortcuts.analyze_profit_margins",
    titleDefault: "Analyze profit margins",
    toolName: "getProfitAnalysis",
    toolParams: { showCanvas: true },
    keywords: ["analyze", "profit", "margins", "profitability"],
  },
  {
    command: "/show",
    titleKey: "chat.shortcuts.show_budget_vs_actual",
    titleDefault: "Show budget versus actual spending",
    toolName: "getBudget",
    toolParams: { showCanvas: true },
    keywords: ["show", "budget", "actual", "spending", "limit"],
  },
  {
    command: "/show",
    titleKey: "chat.shortcuts.show_upcoming_debts",
    titleDefault: "Show upcoming debts due this month",
    toolName: "getDebt",
    toolParams: { status: "active" },
    dateRangePreset: "thisMonth",
    keywords: ["show", "debt", "due", "month", "payable", "receivable"],
  },
  {
    command: "/find",
    titleKey: "chat.shortcuts.find_overdue_debts",
    titleDefault: "Find overdue debts",
    toolName: "getDebt",
    toolParams: { status: "overdue" },
    keywords: ["find", "overdue", "debts", "late"],
  },
  {
    command: "/analyze",
    titleKey: "chat.shortcuts.analyze_debt_risk",
    titleDefault: "Analyze debt risk and aging",
    toolName: "getDebt",
    toolParams: { showCanvas: true },
    keywords: ["analyze", "debt", "risk", "aging", "receivable", "payable"],
  },
  {
    command: "/show",
    titleKey: "chat.shortcuts.show_account_balances",
    titleDefault: "Show account balances",
    toolName: "getAccountBalances",
    toolParams: {},
    keywords: ["show", "account", "balances", "bank", "accounts"],
  },
  {
    command: "/show",
    titleKey: "chat.shortcuts.show_latest_invoices",
    titleDefault: "Show latest invoices",
    toolName: "getInvoices",
    toolParams: { pageSize: 10, sort: ["createdAt", "desc"] },
    keywords: ["show", "latest", "invoices", "recent"],
  },
  {
    command: "/find",
    titleKey: "chat.shortcuts.find_unpaid_invoices",
    titleDefault: "Find unpaid invoices",
    toolName: "getInvoices",
    toolParams: { statuses: ["unpaid"], pageSize: 20 },
    keywords: ["find", "unpaid", "invoices", "outstanding"],
  },
  {
    command: "/find",
    titleKey: "chat.shortcuts.find_overdue_invoices",
    titleDefault: "Find overdue invoices",
    toolName: "getInvoices",
    toolParams: { statuses: ["overdue"], pageSize: 20 },
    keywords: ["find", "overdue", "invoices", "late"],
  },
  {
    command: "/show",
    titleKey: "chat.shortcuts.show_contacts",
    titleDefault: "Show contacts",
    toolName: "getContacts",
    toolParams: { pageSize: 10 },
    keywords: ["show", "contacts", "clients", "list"],
  },
  {
    command: "/find",
    titleKey: "chat.shortcuts.find_top_contacts",
    titleDefault: "Find top contacts",
    toolName: "getContacts",
    toolParams: { pageSize: 10 },
    keywords: ["find", "top", "contacts", "clients"],
  },
  {
    command: "/show",
    titleKey: "chat.shortcuts.show_cash_flow",
    titleDefault: "Show cash flow",
    toolName: "getCashFlow",
    toolParams: { showCanvas: true },
    keywords: ["show", "cash", "flow", "income", "expenses"],
  },
  {
    command: "/show",
    titleKey: "chat.shortcuts.show_cash_flow_this_month",
    titleDefault: "Show cash flow this month",
    toolName: "getCashFlow",
    toolParams: { showCanvas: true },
    dateRangePreset: "thisMonth",
    keywords: ["show", "cash", "flow", "month", "this month"],
  },
  {
    command: "/analyze",
    titleKey: "chat.shortcuts.analyze_cash_flow_trends",
    titleDefault: "Analyze cash flow trends",
    toolName: "getCashFlow",
    toolParams: { showCanvas: true },
    keywords: ["analyze", "cash", "flow", "trends", "patterns"],
  },
  {
    command: "/show",
    titleKey: "chat.shortcuts.show_expenses",
    titleDefault: "Show expenses",
    toolName: "getExpenses",
    toolParams: { showCanvas: true },
    keywords: ["show", "expenses", "costs", "spending"],
  },
  {
    command: "/show",
    titleKey: "chat.shortcuts.show_expenses_this_month",
    titleDefault: "Show expenses this month",
    toolName: "getExpenses",
    toolParams: { showCanvas: true },
    dateRangePreset: "thisMonth",
    keywords: ["show", "expenses", "month", "this month"],
  },
  {
    command: "/analyze",
    titleKey: "chat.shortcuts.analyze_expense_trends",
    titleDefault: "Analyze expense trends",
    toolName: "getExpenses",
    toolParams: { showCanvas: true },
    keywords: ["analyze", "expense", "trends", "patterns"],
  },
];
