export const DEFAULT_INCOME_CATEGORIES = [
  "💵 Salary",
  "💰 Allowance",
  "💵 Petty cash",
  "🏅 Bonus",
  "🐒 Chip in",
  "💰 Freelance",
  "Other",
];

export const DEFAULT_EXPENSE_CATEGORIES = [
  "🍜 Food",
  "🧑‍🤝‍🧑 Social Life",
  "🐶 Pets",
  "🚕 Transport",
  "🪑 Household",
  "🧥 Apparel",
  "💄 Beauty",
  "🧘 Health",
  "📙 Education",
  "🎁 Gift",
  "⚽ Sport",
  "🧣 Laundry",
  "☕ Coffee",
  "💹 Investment",
  "🏡 Rent",
  "💸 Subscription",
  "🛵 Motorbikes",
  "🤖 Hobby",
  "💳 Credit",
  "📶 Internet",
  "🏡 Parents",
  "📚 Hobby",
  "💵 Salary",
  "Other",
];
